# Generated by Django 4.2.2 on 2023-06-27 00:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("survey", "0003_alter_question_survey"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="type",
            field=models.CharField(
                choices=[
                    ("PLAIN_TEXT", "plain text"),
                    ("SELECT", "select"),
                    ("MULTISELECT", "multIselect"),
                ],
                default="PLAIN_TEXT",
                max_length=256,
            ),
        ),
        migrations.CreateModel(
            name="Value",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=256)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="values",
                        to="survey.question",
                    ),
                ),
            ],
        ),
    ]
