# Generated by Django 4.2.2 on 2023-06-27 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("survey", "0004_question_type_value"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Value",
            new_name="QuestionValue",
        ),
    ]
