# Generated by Django 4.2.2 on 2023-06-29 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("survey", "0005_rename_value_questionvalue"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="order",
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name="questionvalue",
            name="order",
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
